version: 2
jobs:
  build:
    working_directory: ~/aneris
    docker:
      - image: docker:17.05.0-ce-git
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: ls
          command: pwd && ls
      - run:
          name: Build Py2 Docker Image
          command: /bin/bash -c "ln -s ci/py2/Dockerfile Dockerfile && docker build -t aneris/aneris:py2 ."
      - run:
          name: Python2 Tests
          command:  docker run aneris/aneris:py2 python2 -m pytest -v /aneris/tests
      - run:
          name: Build Py3 Docker Image
          command: /bin/bash -c "ln -s ci/py3/Dockerfile Dockerfile && docker build -t aneris/aneris:py3 ."
      - run:
          name: Python3 Tests
          command:  docker run aneris/aneris:py3 python3 -m pytest -v /aneris/tests